INFO 2025-03-16 14:13:53,583 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:14:24,852 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:14:24,868 log Internal Server Error: /api/rides/match/
ERROR 2025-03-16 14:14:24,868 basehttp "POST /api/rides/match/ HTTP/1.1" 500 50
INFO 2025-03-16 14:16:50,445 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-16 14:16:50,770 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:17:01,980 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/matching_service.py changed, reloading.
INFO 2025-03-16 14:17:02,257 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:17:13,014 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:17:13,025 matching_service Error calculating distance score: 'MatchingService' object has no attribute 'calculate_distance'
INFO 2025-03-16 14:17:13,529 basehttp "POST /api/rides/match/ HTTP/1.1" 200 541
INFO 2025-03-16 14:24:35,888 basehttp "OPTIONS /api/rides/auth/login/ HTTP/1.1" 200 0
INFO 2025-03-16 14:24:36,090 basehttp "POST /api/rides/auth/login/ HTTP/1.1" 200 135
INFO 2025-03-16 14:29:06,774 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/matching_service.py changed, reloading.
INFO 2025-03-16 14:29:07,105 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:31:19,449 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/models.py changed, reloading.
INFO 2025-03-16 14:31:19,808 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:31:25,963 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 14:31:26,243 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:31:33,430 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-16 14:31:33,703 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:31:41,900 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-16 14:31:42,205 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:31:48,365 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/urls.py changed, reloading.
INFO 2025-03-16 14:31:48,562 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 14:32:26,924 basehttp "GET /admin/matching/ride/ HTTP/1.1" 200 13407
INFO 2025-03-16 14:32:26,971 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:26,977 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:26,981 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:26,982 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:26,983 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:26,987 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:26,989 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:26,991 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:26,994 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:26,996 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:26,996 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:27,000 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:26,997 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:27,005 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:27,006 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:27,007 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:27,011 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:27,014 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:27,051 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:27,051 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:27,052 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:27,136 basehttp "GET /admin/matching/ride/ HTTP/1.1" 200 13407
INFO 2025-03-16 14:32:27,155 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:27,155 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:27,157 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:27,158 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:27,159 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:27,160 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:27,162 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:27,162 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:27,163 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:27,163 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:27,165 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:27,166 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:27,167 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:27,170 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:27,175 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:27,175 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:27,179 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:27,179 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:27,204 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:27,204 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:27,205 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:29,085 basehttp "GET /admin/matching/ride/?o=2 HTTP/1.1" 200 13831
INFO 2025-03-16 14:32:29,143 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:29,188 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:29,189 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:29,189 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:29,193 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:29,199 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:29,200 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:29,203 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:29,206 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:29,206 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:29,206 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:29,213 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:29,213 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:29,217 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:29,221 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:29,223 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:29,228 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:29,229 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:29,244 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:29,244 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:29,244 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-16 14:32:29,245 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:32,390 basehttp "GET /admin/matching/ride/?o=-2 HTTP/1.1" 200 13850
INFO 2025-03-16 14:32:32,448 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:32,457 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:32,463 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:32,463 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:32,464 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:32,469 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:32,477 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:32,479 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:32,480 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:32,480 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:32,483 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:32,485 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:32,486 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:32,487 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:32,488 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:32,490 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:32,493 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:32,502 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:32,538 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:32,538 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-16 14:32:32,538 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:32,539 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:33,752 basehttp "GET /admin/matching/ride/?o=3.-2 HTTP/1.1" 200 14254
INFO 2025-03-16 14:32:33,780 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:33,780 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:33,780 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:33,781 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:33,782 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:33,783 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:33,791 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:33,795 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:33,797 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:33,797 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:33,799 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:33,801 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:33,802 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:33,804 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:33,807 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:33,808 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:33,812 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:33,826 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:33,847 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-16 14:32:33,847 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:33,847 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:33,848 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:40,258 basehttp "GET /admin/matching/ride/?o=4.3.-2 HTTP/1.1" 200 14604
INFO 2025-03-16 14:32:40,395 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-16 14:32:40,396 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-16 14:32:40,402 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-16 14:32:40,403 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-16 14:32:40,411 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-16 14:32:40,411 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-16 14:32:40,412 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-16 14:32:40,414 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-16 14:32:40,418 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 14:32:40,418 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-16 14:32:40,420 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-16 14:32:40,421 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-16 14:32:40,423 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-16 14:32:40,424 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-16 14:32:40,431 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-16 14:32:40,431 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-16 14:32:40,435 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-16 14:32:40,443 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-16 14:32:40,458 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:32:40,459 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-16 14:32:40,459 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-16 14:32:40,459 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-16 14:47:30,612 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:47:30,615 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:47:30,781 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:47:30,789 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:47:30,818 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:47:30,819 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:51:35,069 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:51:35,069 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:51:35,105 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:51:35,113 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:51:35,114 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:51:35,116 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:51:36,670 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:51:36,694 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:51:36,695 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:51:43,371 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:51:43,399 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:51:43,401 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:54:33,120 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:54:33,120 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:54:33,165 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:33,174 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:33,177 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:54:33,177 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:54:46,103 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:46,105 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168488
ERROR 2025-03-16 14:54:46,119 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:46,121 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168488
ERROR 2025-03-16 14:54:47,784 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:47,786 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168488
ERROR 2025-03-16 14:54:48,629 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:48,630 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168488
INFO 2025-03-16 14:54:59,294 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:54:59,294 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:54:59,320 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:59,329 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:54:59,331 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:54:59,332 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:55:00,783 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:55:00,783 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:55:00,813 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:55:00,816 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:55:00,826 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:55:00,828 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 14:56:58,912 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 14:56:58,913 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
ERROR 2025-03-16 14:56:58,948 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:56:58,955 log Internal Server Error: /api/rides/ride-requests/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matching_riderequest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matching_riderequest
ERROR 2025-03-16 14:56:58,958 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
ERROR 2025-03-16 14:56:58,958 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 500 168754
INFO 2025-03-16 15:06:57,968 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:06:57,983 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 2
INFO 2025-03-16 15:07:06,874 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:07:06,874 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:07:06,879 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 2
INFO 2025-03-16 15:07:06,885 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 2
INFO 2025-03-16 15:07:25,753 basehttp "GET /admin/matching/ride/?o=4.3.-2 HTTP/1.1" 200 14604
INFO 2025-03-16 15:07:25,807 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,807 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,807 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,812 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,814 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,814 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,815 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,816 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,817 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,818 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,820 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,820 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,820 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,821 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,821 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 15:07:25,822 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,827 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,832 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,841 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,842 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,843 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:07:25,843 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:07:28,679 basehttp "GET /admin/matching/ride/?o=4.3.-2 HTTP/1.1" 200 14604
INFO 2025-03-16 15:07:28,689 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 15:07:50,347 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:07:50,350 log Unauthorized: /api/rides/match/
WARNING 2025-03-16 15:07:50,351 basehttp "POST /api/rides/match/ HTTP/1.1" 401 58
INFO 2025-03-16 15:08:04,928 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:08:04,930 log Unauthorized: /api/rides/match/
WARNING 2025-03-16 15:08:04,930 basehttp "POST /api/rides/match/ HTTP/1.1" 401 58
INFO 2025-03-16 15:08:34,718 basehttp "OPTIONS /api/rides/auth/login/ HTTP/1.1" 200 0
INFO 2025-03-16 15:08:34,930 basehttp "POST /api/rides/auth/login/ HTTP/1.1" 200 137
INFO 2025-03-16 15:08:48,165 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:08:48,172 log Bad Request: /api/rides/match/
WARNING 2025-03-16 15:08:48,172 basehttp "POST /api/rides/match/ HTTP/1.1" 400 44
INFO 2025-03-16 15:09:37,770 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
ERROR 2025-03-16 15:09:37,801 matching_service Error calculating distance score: 'MatchingService' object has no attribute 'calculate_distance'
ERROR 2025-03-16 15:09:41,264 views Error in matching service: NOT NULL constraint failed: matching_ride.driver_id
ERROR 2025-03-16 15:09:41,264 log Internal Server Error: /api/rides/match/
ERROR 2025-03-16 15:09:41,264 basehttp "POST /api/rides/match/ HTTP/1.1" 500 90
INFO 2025-03-16 15:10:49,655 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/matching_service.py changed, reloading.
INFO 2025-03-16 15:10:50,012 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:11:12,326 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-16 15:11:12,615 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:11:28,513 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:11:28,513 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:11:28,526 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 2
INFO 2025-03-16 15:11:28,526 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 2
INFO 2025-03-16 15:11:37,096 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
INFO 2025-03-16 15:11:37,734 basehttp "POST /api/rides/match/ HTTP/1.1" 200 492
INFO 2025-03-16 15:12:20,232 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:12:20,233 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:12:20,246 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 135
INFO 2025-03-16 15:12:20,247 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 135
INFO 2025-03-16 15:14:36,810 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 15:14:37,137 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:15:00,477 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 15:15:00,755 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:15:10,495 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:15:10,495 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:15:10,506 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:15:10,506 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:15:38,974 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:15:38,974 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:15:39,000 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:15:39,002 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:22:14,674 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:22:14,674 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:22:14,689 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:22:14,689 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:24:30,627 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:24:30,631 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:25:03,281 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:25:03,295 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:25:03,295 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:25:14,786 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:25:14,787 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:25:14,799 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:25:14,799 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:25:19,639 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:25:19,642 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:25:19,642 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:32:33,832 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:32:33,833 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:32:33,846 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:32:33,847 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:32:40,001 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:32:40,012 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:32:40,012 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:33:55,383 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:33:55,383 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:33:55,403 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:33:55,403 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:33:59,428 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:33:59,432 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:33:59,432 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:34:28,258 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:34:28,258 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:34:28,269 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:34:28,269 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:34:33,379 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:34:33,382 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:34:33,382 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:35:56,442 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:35:56,443 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:35:56,475 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:35:56,475 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:36:08,490 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
WARNING 2025-03-16 15:36:08,505 log Bad Request: /api/rides/ride-requests/1/respond/
WARNING 2025-03-16 15:36:08,506 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 400 56
INFO 2025-03-16 15:39:20,301 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 15:39:20,686 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:40:58,047 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-16 15:40:58,393 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:41:44,526 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:41:44,526 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:41:44,553 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:41:44,554 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 425
INFO 2025-03-16 15:41:53,784 basehttp "OPTIONS /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 0
INFO 2025-03-16 15:41:53,811 basehttp "POST /api/rides/ride-requests/1/respond/ HTTP/1.1" 200 481
INFO 2025-03-16 15:42:10,552 basehttp "GET /admin/matching/ride/?o=4.3.-2 HTTP/1.1" 200 15094
INFO 2025-03-16 15:42:10,627 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,627 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,627 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,627 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,628 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,629 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,630 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,630 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,631 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,632 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,632 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,634 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,636 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,637 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,637 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,638 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 15:42:10,643 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,650 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,686 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,686 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,687 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:42:10,687 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-03-16 15:42:17,545 basehttp "GET /admin/matching/passenger/ HTTP/1.1" 200 12724
INFO 2025-03-16 15:42:17,586 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 15:42:19,514 basehttp "GET /admin/matching/ride/ HTTP/1.1" 200 13866
INFO 2025-03-16 15:42:19,593 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 15:42:35,928 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:42:35,928 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:42:35,959 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 426
INFO 2025-03-16 15:42:35,959 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 426
INFO 2025-03-16 15:45:22,673 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 15:45:23,079 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 15:46:13,640 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:46:13,641 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 15:46:13,680 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 478
INFO 2025-03-16 15:46:13,681 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 478
INFO 2025-03-16 15:54:46,055 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/serializers.py changed, reloading.
INFO 2025-03-16 15:54:46,391 autoreload Watching for file changes with StatReloader
INFO 2025-03-16 16:00:35,122 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 16:00:35,124 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 16:00:35,163 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 524
INFO 2025-03-16 16:00:35,164 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 524
INFO 2025-03-16 16:04:53,210 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 16:04:53,210 basehttp "OPTIONS /api/rides/ride-requests/ HTTP/1.1" 200 0
INFO 2025-03-16 16:04:53,227 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 524
INFO 2025-03-16 16:04:53,227 basehttp "GET /api/rides/ride-requests/ HTTP/1.1" 200 524
INFO 2025-03-17 15:58:46,988 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 15:58:47,554 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 15:59:11,115 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 15:59:11,460 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 16:00:49,636 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-17 16:00:50,043 autoreload Watching for file changes with StatReloader
WARNING 2025-03-17 16:02:15,458 log Not Found: /navigation
WARNING 2025-03-17 16:02:15,459 basehttp "GET /navigation HTTP/1.1" 404 2707
INFO 2025-03-17 16:02:27,962 basehttp "GET /api/rides/navigation HTTP/1.1" 301 0
WARNING 2025-03-17 16:02:27,965 log Unauthorized: /api/rides/navigation/
WARNING 2025-03-17 16:02:27,965 basehttp "GET /api/rides/navigation/ HTTP/1.1" 401 58
INFO 2025-03-17 16:02:52,931 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-17 16:02:53,268 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 16:03:02,607 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-17 16:03:02,968 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 16:03:03,943 basehttp "GET /api/rides/navigation HTTP/1.1" 301 0
WARNING 2025-03-17 16:03:03,944 log Method Not Allowed: /api/rides/navigation/
WARNING 2025-03-17 16:03:03,945 basehttp "GET /api/rides/navigation/ HTTP/1.1" 405 40
ERROR 2025-03-17 16:03:19,055 log Internal Server Error: /api/rides/navigation
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:3003/api/rides/navigation/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2025-03-17 16:03:19,056 basehttp "POST /api/rides/navigation HTTP/1.1" 500 68465
ERROR 2025-03-17 16:03:25,714 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
ERROR 2025-03-17 16:03:25,716 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117754
INFO 2025-03-17 16:05:26,763 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 16:05:27,107 autoreload Watching for file changes with StatReloader
ERROR 2025-03-17 16:06:25,173 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
ERROR 2025-03-17 16:06:25,176 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117756
INFO 2025-03-17 16:06:49,171 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 16:06:49,538 autoreload Watching for file changes with StatReloader
ERROR 2025-03-17 16:06:51,511 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (The provided API key is invalid. )
ERROR 2025-03-17 16:06:51,514 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117598
INFO 2025-03-17 16:06:57,940 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 16:06:58,273 autoreload Watching for file changes with StatReloader
ERROR 2025-03-17 16:07:00,983 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
ERROR 2025-03-17 16:07:00,986 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117754
INFO 2025-03-17 16:10:31,382 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 16:10:31,740 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 16:10:33,896 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py changed, reloading.
INFO 2025-03-17 16:10:34,105 autoreload Watching for file changes with StatReloader
ERROR 2025-03-17 16:10:39,923 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
ERROR 2025-03-17 16:10:39,926 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117757
ERROR 2025-03-17 16:12:21,380 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 400, in create
    'text': sum(leg.get('distance', {}).get('text', '0 km') for leg in route_data[best_route_index]['legs']),
            ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'str'
ERROR 2025-03-17 16:12:21,383 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 99122
INFO 2025-03-17 16:13:23,046 autoreload /Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py changed, reloading.
INFO 2025-03-17 16:13:23,384 autoreload Watching for file changes with StatReloader
ERROR 2025-03-17 16:13:25,897 log Internal Server Error: /api/rides/navigation/
Traceback (most recent call last):
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/views.py", line 370, in create
    route_data = navigation_service.get_optimal_route(
        origin=serializer.validated_data['origin'],
        destination=serializer.validated_data['destination'],
        waypoints=serializer.validated_data.get('waypoints')
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/matching/services/navigation_service.py", line 31, in get_optimal_route
    directions_result = self.client.directions(
        origin=origin_str,
    ...<3 lines>...
        mode="driving"
    )
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 445, in wrapper
    result = func(*args, **kwargs)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/directions.py", line 153, in directions
    return client._request("/maps/api/directions/json", params).get("routes", [])
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 340, in _request
    result = self._get_body(response)
  File "/Users/hammedbalogun/Desktop/ride_mgn_system-main/venv/lib/python3.13/site-packages/googlemaps/client.py", line 369, in _get_body
    raise googlemaps.exceptions.ApiError(api_status,
                                         body.get("error_message"))
googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
ERROR 2025-03-17 16:13:25,903 basehttp "POST /api/rides/navigation/ HTTP/1.1" 500 117757
INFO 2025-03-17 16:13:36,930 basehttp "POST /api/rides/navigation/ HTTP/1.1" 200 18249
INFO 2025-03-17 16:20:12,004 basehttp "OPTIONS /api/rides/match/ HTTP/1.1" 200 0
INFO 2025-03-17 16:20:12,593 basehttp "POST /api/rides/match/ HTTP/1.1" 200 984
